Slava lunek page object
slavalunek/SauceDemo pull request #2
Opened 2022-06-29 13:18 UTC by slavalunek

2022-06-29 14:50 UTC, testershmester requested changes
в целом ок, поправь комменты

2022-06-29 14:50 UTC, testershmester commented on src/test/java/org/example/CartTest.java
> +    }
тесты разделяй между собой пустой строкой

2022-06-29 14:50 UTC, testershmester commented on src/main/java/org/exumple/pages/CartPage.java
> +    private final By REMOVE = By.cssSelector("#remove-sauce-labs-backpack");
это плохой локатор, он завязан на айди конкретного продукта. нужно делать по аналогии как мы писали локатор для добавления продукта в корзину

2022-06-29 14:50 UTC, testershmester commented on src/main/java/org/exumple/pages/CartPage.java
> +    private final By BURGER_MENU_BUTTON = By.cssSelector("#react-burger-menu-btn");
# - это поиск по айди, в селениуме прямо метод отдельный есть для этого

2022-06-29 14:50 UTC, testershmester commented on src/main/java/org/exumple/pages/CartPage.java
> +    public boolean BurgerMenu(){
метод с маленькой буквы

2022-06-29 14:50 UTC, testershmester commented on src/main/java/org/exumple/pages/CartPage.java
> +    public WebElement removeProduct() {
метод называется удалить продукт, но здесь не вижу ничего кроме поиска элемента?

2022-06-29 14:50 UTC, testershmester commented on src/main/java/org/exumple/pages/CartPage.java
> +    public int getInventoryItemName2() {
имя для метода должно отраажаать суть того что в методе происходит. таакже цифр в именах быть не должно

2022-06-29 14:50 UTC, testershmester commented on src/main/java/org/exumple/pages/CartPage.java
> +public WebElement checkoutYourInformation(){
тоже самое как и с ремув. если метод ищет и возвращает элемент, то должен называться соответственно, т.е. getCheckoutPageTitle или что-то такое по смыслу

2022-06-29 14:50 UTC, testershmester commented on src/main/java/org/exumple/pages/ProductsPage.java
> +    private final By TITLE = By.cssSelector(".title");
а в чем разница с 9 строкой? может этот тайтл должен быть в карт пейдж?

2022-06-30 06:49 UTC, slavalunek commented on src/main/java/org/exumple/pages/ProductsPage.java
> +    private final By TITLE = By.cssSelector(".title");
я же TITLE_CART использую в тесте на странице ProductsTest

2022-07-12 14:44 UTC, closed without merging